-- MySQL Script generated by MySQL Workbench
-- Sun Jun 11 22:10:21 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`EstadoCivil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EstadoCivil` (
  `id_estado_civil` INT NOT NULL AUTO_INCREMENT,
  `descricao_estado_civil` VARCHAR(45) NULL,
  PRIMARY KEY (`id_estado_civil`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Sexo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Sexo` (
  `id_sexo` INT NOT NULL AUTO_INCREMENT,
  `descricao_sexo` VARCHAR(45) NULL,
  PRIMARY KEY (`id_sexo`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`DonoEstudio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DonoEstudio` (
  `id_dono_estudio` INT NOT NULL AUTO_INCREMENT,
  `cpf_dono` INT NULL,
  `nome_dono` VARCHAR(45) NULL,
  `EstadoCivil_id_estado_civil` INT NOT NULL,
  `Sexo_id_sexo` INT NOT NULL,
  PRIMARY KEY (`id_dono_estudio`, `EstadoCivil_id_estado_civil`, `Sexo_id_sexo`),
  INDEX `fk_DonoEstudio_EstadoCivil1_idx` (`EstadoCivil_id_estado_civil` ASC),
  INDEX `fk_DonoEstudio_Sexo1_idx` (`Sexo_id_sexo` ASC),
  CONSTRAINT `fk_DonoEstudio_EstadoCivil1`
    FOREIGN KEY (`EstadoCivil_id_estado_civil`)
    REFERENCES `mydb`.`EstadoCivil` (`id_estado_civil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DonoEstudio_Sexo1`
    FOREIGN KEY (`Sexo_id_sexo`)
    REFERENCES `mydb`.`Sexo` (`id_sexo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Estudio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Estudio` (
  `id_estudio` INT NOT NULL AUTO_INCREMENT,
  `nome_estudio` VARCHAR(45) NULL,
  `data_fundacao_estudio` DATE NULL,
  `faturamento_ano_anterior` FLOAT NULL,
  `DonoEstudio_id_dono_estudio` INT NOT NULL,
  PRIMARY KEY (`id_estudio`, `DonoEstudio_id_dono_estudio`),
  INDEX `fk_Estudio_DonoEstudio1_idx` (`DonoEstudio_id_dono_estudio` ASC),
  CONSTRAINT `fk_Estudio_DonoEstudio1`
    FOREIGN KEY (`DonoEstudio_id_dono_estudio`)
    REFERENCES `mydb`.`DonoEstudio` (`id_dono_estudio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Filme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Filme` (
  `id_filme` INT NOT NULL AUTO_INCREMENT,
  `nome_filme` VARCHAR(45) NULL,
  `copyright_filme` MEDIUMTEXT NULL,
  `qtd_meses_producao` INT NULL,
  `ano_lancamento` YEAR NULL,
  `custo_total_producao` FLOAT NULL,
  `Estudio_id_estudio` INT NOT NULL,
  PRIMARY KEY (`id_filme`, `Estudio_id_estudio`),
  INDEX `fk_Filme_Estudio1_idx` (`Estudio_id_estudio` ASC),
  CONSTRAINT `fk_Filme_Estudio1`
    FOREIGN KEY (`Estudio_id_estudio`)
    REFERENCES `mydb`.`Estudio` (`id_estudio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Pais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pais` (
  `id_pais` INT NOT NULL AUTO_INCREMENT,
  `nome_pais` VARCHAR(45) NULL,
  `DDI` INT NULL,
  PRIMARY KEY (`id_pais`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`UF`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`UF` (
  `id_uf` INT NOT NULL AUTO_INCREMENT,
  `nome_uf` VARCHAR(45) NULL,
  `Pais_id_pais` INT NOT NULL,
  PRIMARY KEY (`id_uf`, `Pais_id_pais`),
  INDEX `fk_UF_Pais1_idx` (`Pais_id_pais` ASC),
  CONSTRAINT `fk_UF_Pais1`
    FOREIGN KEY (`Pais_id_pais`)
    REFERENCES `mydb`.`Pais` (`id_pais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cidade` (
  `id_cidade` INT NOT NULL AUTO_INCREMENT,
  `nome_cidade` VARCHAR(45) NULL,
  `DDD` INT NULL,
  `UF_id_uf` INT NOT NULL,
  `UF_Pais_id_pais` INT NOT NULL,
  PRIMARY KEY (`id_cidade`, `UF_id_uf`, `UF_Pais_id_pais`),
  INDEX `fk_Cidade_UF1_idx` (`UF_id_uf` ASC, `UF_Pais_id_pais` ASC),
  CONSTRAINT `fk_Cidade_UF1`
    FOREIGN KEY (`UF_id_uf` , `UF_Pais_id_pais`)
    REFERENCES `mydb`.`UF` (`id_uf` , `Pais_id_pais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Ator`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ator` (
  `id_ator` INT NOT NULL AUTO_INCREMENT,
  `cpf_ator` INT NULL,
  `nome_artistico_ator` VARCHAR(45) NULL,
  `seguro_social_ator` MEDIUMTEXT NULL,
  `data_nascimento_ator` DATE NULL,
  `Sexo_id_sexo` INT NOT NULL,
  `EstadoCivil_id_estado_civil` INT NOT NULL,
  `Cidade_id_cidade` INT NOT NULL,
  `Cidade_UF_id_uf` INT NOT NULL,
  `Cidade_UF_Pais_id_pais` INT NOT NULL,
  PRIMARY KEY (`id_ator`, `EstadoCivil_id_estado_civil`, `Cidade_id_cidade`, `Cidade_UF_id_uf`, `Cidade_UF_Pais_id_pais`, `Sexo_id_sexo`),
  INDEX `fk_Ator_EstadoCivil1_idx` (`EstadoCivil_id_estado_civil` ASC),
  INDEX `fk_Ator_Sexo1_idx` (`Sexo_id_sexo` ASC),
  INDEX `fk_Ator_Cidade1_idx` (`Cidade_id_cidade` ASC, `Cidade_UF_id_uf` ASC, `Cidade_UF_Pais_id_pais` ASC),
  CONSTRAINT `fk_Ator_EstadoCivil1`
    FOREIGN KEY (`EstadoCivil_id_estado_civil`)
    REFERENCES `mydb`.`EstadoCivil` (`id_estado_civil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ator_Sexo1`
    FOREIGN KEY (`Sexo_id_sexo`)
    REFERENCES `mydb`.`Sexo` (`id_sexo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ator_Cidade1`
    FOREIGN KEY (`Cidade_id_cidade` , `Cidade_UF_id_uf` , `Cidade_UF_Pais_id_pais`)
    REFERENCES `mydb`.`Cidade` (`id_cidade` , `UF_id_uf` , `UF_Pais_id_pais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Diretor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Diretor` (
  `idDiretor` INT NOT NULL AUTO_INCREMENT,
  `cpf_diretor` INT NULL,
  `nome_diretor` VARCHAR(45) NULL,
  `EstadoCivil_id_estado_civil` INT NOT NULL,
  `Sexo_id_sexo` INT NOT NULL,
  `Cidade_id_cidade` INT NOT NULL,
  `Cidade_UF_id_uf` INT NOT NULL,
  `Cidade_UF_Pais_id_pais` INT NOT NULL,
  PRIMARY KEY (`idDiretor`, `EstadoCivil_id_estado_civil`, `Sexo_id_sexo`, `Cidade_id_cidade`, `Cidade_UF_id_uf`, `Cidade_UF_Pais_id_pais`),
  INDEX `fk_Diretor_EstadoCivil1_idx` (`EstadoCivil_id_estado_civil` ASC),
  INDEX `fk_Diretor_Sexo1_idx` (`Sexo_id_sexo` ASC),
  INDEX `fk_Diretor_Cidade1_idx` (`Cidade_id_cidade` ASC, `Cidade_UF_id_uf` ASC, `Cidade_UF_Pais_id_pais` ASC),
  CONSTRAINT `fk_Diretor_EstadoCivil1`
    FOREIGN KEY (`EstadoCivil_id_estado_civil`)
    REFERENCES `mydb`.`EstadoCivil` (`id_estado_civil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Diretor_Sexo1`
    FOREIGN KEY (`Sexo_id_sexo`)
    REFERENCES `mydb`.`Sexo` (`id_sexo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Diretor_Cidade1`
    FOREIGN KEY (`Cidade_id_cidade` , `Cidade_UF_id_uf` , `Cidade_UF_Pais_id_pais`)
    REFERENCES `mydb`.`Cidade` (`id_cidade` , `UF_id_uf` , `UF_Pais_id_pais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`ContratoAtorFilme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ContratoAtorFilme` (
  `cache_ator` FLOAT NULL,
  `Filme_id_filme` INT NOT NULL,
  `Ator_id_ator` INT NOT NULL,
  PRIMARY KEY (`Filme_id_filme`, `Ator_id_ator`),
  INDEX `fk_Filme_has_Ator_Ator1_idx` (`Ator_id_ator` ASC),
  CONSTRAINT `fk_Filme_has_Ator_Filme1`
    FOREIGN KEY (`Filme_id_filme`)
    REFERENCES `mydb`.`Filme` (`id_filme`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Filme_has_Ator_Ator1`
    FOREIGN KEY (`Ator_id_ator`)
    REFERENCES `mydb`.`Ator` (`id_ator`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Personagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Personagem` (
  `id_personagem` INT NOT NULL AUTO_INCREMENT,
  `nome_personagem` VARCHAR(45) NULL,
  `Sexo_id_sexo` INT NOT NULL,
  `ContratoAtorFilme_Filme_id_filme` INT NOT NULL,
  `ContratoAtorFilme_Ator_id_ator` INT NOT NULL,
  PRIMARY KEY (`id_personagem`, `Sexo_id_sexo`, `ContratoAtorFilme_Filme_id_filme`, `ContratoAtorFilme_Ator_id_ator`),
  INDEX `fk_Personagem_Sexo1_idx` (`Sexo_id_sexo` ASC),
  INDEX `fk_Personagem_ContratoAtorFilme1_idx` (`ContratoAtorFilme_Filme_id_filme` ASC, `ContratoAtorFilme_Ator_id_ator` ASC),
  CONSTRAINT `fk_Personagem_Sexo1`
    FOREIGN KEY (`Sexo_id_sexo`)
    REFERENCES `mydb`.`Sexo` (`id_sexo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Personagem_ContratoAtorFilme1`
    FOREIGN KEY (`ContratoAtorFilme_Filme_id_filme` , `ContratoAtorFilme_Ator_id_ator`)
    REFERENCES `mydb`.`ContratoAtorFilme` (`Filme_id_filme` , `Ator_id_ator`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Bairro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Bairro` (
  `id_bairro` INT NOT NULL AUTO_INCREMENT,
  `nome_bairro` VARCHAR(45) NULL,
  `Cidade_id_cidade` INT NOT NULL,
  `Cidade_UF_id_uf` INT NOT NULL,
  `Cidade_UF_Pais_id_pais` INT NOT NULL,
  PRIMARY KEY (`id_bairro`, `Cidade_id_cidade`, `Cidade_UF_id_uf`, `Cidade_UF_Pais_id_pais`),
  INDEX `fk_Bairro_Cidade1_idx` (`Cidade_id_cidade` ASC, `Cidade_UF_id_uf` ASC, `Cidade_UF_Pais_id_pais` ASC),
  CONSTRAINT `fk_Bairro_Cidade1`
    FOREIGN KEY (`Cidade_id_cidade` , `Cidade_UF_id_uf` , `Cidade_UF_Pais_id_pais`)
    REFERENCES `mydb`.`Cidade` (`id_cidade` , `UF_id_uf` , `UF_Pais_id_pais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Rua`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Rua` (
  `id_rua` INT NOT NULL AUTO_INCREMENT,
  `cep_rua` INT NULL,
  `nome_rua` VARCHAR(45) NULL,
  `Bairro_id_bairro` INT NOT NULL,
  `Bairro_Cidade_id_cidade` INT NOT NULL,
  `Bairro_Cidade_UF_id_uf` INT NOT NULL,
  `Bairro_Cidade_UF_Pais_id_pais` INT NOT NULL,
  PRIMARY KEY (`id_rua`, `Bairro_id_bairro`, `Bairro_Cidade_id_cidade`, `Bairro_Cidade_UF_id_uf`, `Bairro_Cidade_UF_Pais_id_pais`),
  INDEX `fk_Rua_Bairro1_idx` (`Bairro_id_bairro` ASC, `Bairro_Cidade_id_cidade` ASC, `Bairro_Cidade_UF_id_uf` ASC, `Bairro_Cidade_UF_Pais_id_pais` ASC),
  CONSTRAINT `fk_Rua_Bairro1`
    FOREIGN KEY (`Bairro_id_bairro` , `Bairro_Cidade_id_cidade` , `Bairro_Cidade_UF_id_uf` , `Bairro_Cidade_UF_Pais_id_pais`)
    REFERENCES `mydb`.`Bairro` (`id_bairro` , `Cidade_id_cidade` , `Cidade_UF_id_uf` , `Cidade_UF_Pais_id_pais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`TipoEndereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TipoEndereco` (
  `id_tipo_endereco` INT NOT NULL AUTO_INCREMENT,
  `descricao_tipo_endereco` VARCHAR(45) NULL,
  PRIMARY KEY (`id_tipo_endereco`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Endereco` (
  `id_endereco` INT NOT NULL AUTO_INCREMENT,
  `Rua_id_rua` INT NOT NULL,
  `Rua_Bairro_id_bairro` INT NOT NULL,
  `Rua_Bairro_Cidade_id_cidade` INT NOT NULL,
  `Rua_Bairro_Cidade_UF_id_uf` INT NOT NULL,
  `Rua_Bairro_Cidade_UF_Pais_id_pais` INT NOT NULL,
  `TipoEndereco_id_tipo_endereco` INT NOT NULL,
  `Estudio_id_estudio` INT NULL,
  `DonoEstudio_id_dono_estudio` INT NULL,
  `Ator_id_ator` INT NULL,
  `Diretor_idDiretor` INT NULL,
  PRIMARY KEY (`id_endereco`, `Rua_id_rua`, `Rua_Bairro_id_bairro`, `Rua_Bairro_Cidade_id_cidade`, `Rua_Bairro_Cidade_UF_id_uf`, `Rua_Bairro_Cidade_UF_Pais_id_pais`, `TipoEndereco_id_tipo_endereco`, `DonoEstudio_id_dono_estudio`, `Estudio_id_estudio`, `Ator_id_ator`, `Diretor_idDiretor`),
  INDEX `fk_Endereco_Rua1_idx` (`Rua_id_rua` ASC, `Rua_Bairro_id_bairro` ASC, `Rua_Bairro_Cidade_id_cidade` ASC, `Rua_Bairro_Cidade_UF_id_uf` ASC, `Rua_Bairro_Cidade_UF_Pais_id_pais` ASC),
  INDEX `fk_Endereco_TipoEndereco1_idx` (`TipoEndereco_id_tipo_endereco` ASC),
  INDEX `fk_Endereco_Estudio1_idx` (`Estudio_id_estudio` ASC),
  INDEX `fk_Endereco_DonoEstudio1_idx` (`DonoEstudio_id_dono_estudio` ASC),
  INDEX `fk_Endereco_Ator1_idx` (`Ator_id_ator` ASC),
  INDEX `fk_Endereco_Diretor1_idx` (`Diretor_idDiretor` ASC),
  CONSTRAINT `fk_Endereco_Rua1`
    FOREIGN KEY (`Rua_id_rua` , `Rua_Bairro_id_bairro` , `Rua_Bairro_Cidade_id_cidade` , `Rua_Bairro_Cidade_UF_id_uf` , `Rua_Bairro_Cidade_UF_Pais_id_pais`)
    REFERENCES `mydb`.`Rua` (`id_rua` , `Bairro_id_bairro` , `Bairro_Cidade_id_cidade` , `Bairro_Cidade_UF_id_uf` , `Bairro_Cidade_UF_Pais_id_pais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Endereco_TipoEndereco1`
    FOREIGN KEY (`TipoEndereco_id_tipo_endereco`)
    REFERENCES `mydb`.`TipoEndereco` (`id_tipo_endereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Endereco_Estudio1`
    FOREIGN KEY (`Estudio_id_estudio`)
    REFERENCES `mydb`.`Estudio` (`id_estudio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Endereco_DonoEstudio1`
    FOREIGN KEY (`DonoEstudio_id_dono_estudio`)
    REFERENCES `mydb`.`DonoEstudio` (`id_dono_estudio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Endereco_Ator1`
    FOREIGN KEY (`Ator_id_ator`)
    REFERENCES `mydb`.`Ator` (`id_ator`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Endereco_Diretor1`
    FOREIGN KEY (`Diretor_idDiretor`)
    REFERENCES `mydb`.`Diretor` (`idDiretor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`TipoTelefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TipoTelefone` (
  `id_tipo_telefone` INT NOT NULL AUTO_INCREMENT,
  `descricao_tipo_telefone` VARCHAR(45) NULL,
  PRIMARY KEY (`id_tipo_telefone`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Telefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Telefone` (
  `id_telefone` INT NOT NULL AUTO_INCREMENT,
  `numero_telefone` VARCHAR(45) NULL,
  `TipoTelefone_id_tipo_telefone` INT NOT NULL,
  `DonoEstudio_id_dono_estudio` INT,
  `Diretor_idDiretor` INT,
  `Estudio_id_estudio` INT,
  `Ator_id_ator` INT,
  PRIMARY KEY (`id_telefone`, `TipoTelefone_id_tipo_telefone`, `DonoEstudio_id_dono_estudio`, `Diretor_idDiretor`, `Estudio_id_estudio`, `Ator_id_ator`),
  INDEX `fk_Telefone_TipoTelefone1_idx` (`TipoTelefone_id_tipo_telefone` ASC),
  INDEX `fk_Telefone_DonoEstudio1_idx` (`DonoEstudio_id_dono_estudio` ASC),
  INDEX `fk_Telefone_Diretor1_idx` (`Diretor_idDiretor` ASC),
  INDEX `fk_Telefone_Estudio1_idx` (`Estudio_id_estudio` ASC),
  INDEX `fk_Telefone_Ator1_idx` (`Ator_id_ator` ASC),
  CONSTRAINT `fk_Telefone_TipoTelefone1`
    FOREIGN KEY (`TipoTelefone_id_tipo_telefone`)
    REFERENCES `mydb`.`TipoTelefone` (`id_tipo_telefone`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Telefone_DonoEstudio1`
    FOREIGN KEY (`DonoEstudio_id_dono_estudio`)
    REFERENCES `mydb`.`DonoEstudio` (`id_dono_estudio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Telefone_Diretor1`
    FOREIGN KEY (`Diretor_idDiretor`)
    REFERENCES `mydb`.`Diretor` (`idDiretor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Telefone_Estudio1`
    FOREIGN KEY (`Estudio_id_estudio`)
    REFERENCES `mydb`.`Estudio` (`id_estudio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Telefone_Ator1`
    FOREIGN KEY (`Ator_id_ator`)
    REFERENCES `mydb`.`Ator` (`id_ator`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Papel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Papel` (
  `id_papel` INT NOT NULL AUTO_INCREMENT,
  `descricao_papel` VARCHAR(45) NULL,
  PRIMARY KEY (`id_papel`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`AtorPapel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`AtorPapel` (
  `Papel_id_papel` INT NOT NULL,
  `Ator_id_ator` INT NOT NULL,
  PRIMARY KEY (`Papel_id_papel`, `Ator_id_ator`),
  INDEX `fk_Ator_has_Papel_Papel1_idx` (`Papel_id_papel` ASC),
  INDEX `fk_AtorPapel_Ator1_idx` (`Ator_id_ator` ASC),
  CONSTRAINT `fk_Ator_has_Papel_Papel1`
    FOREIGN KEY (`Papel_id_papel`)
    REFERENCES `mydb`.`Papel` (`id_papel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AtorPapel_Ator1`
    FOREIGN KEY (`Ator_id_ator`)
    REFERENCES `mydb`.`Ator` (`id_ator`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`FilmeDiretor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`FilmeDiretor` (
  `Filme_id_filme` INT NOT NULL,
  `Diretor_idDiretor` INT NOT NULL,
  PRIMARY KEY (`Filme_id_filme`, `Diretor_idDiretor`),
  INDEX `fk_Filme_has_Diretor_Filme1_idx` (`Filme_id_filme` ASC),
  INDEX `fk_FilmeDiretor_Diretor1_idx` (`Diretor_idDiretor` ASC),
  CONSTRAINT `fk_Filme_has_Diretor_Filme1`
    FOREIGN KEY (`Filme_id_filme`)
    REFERENCES `mydb`.`Filme` (`id_filme`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FilmeDiretor_Diretor1`
    FOREIGN KEY (`Diretor_idDiretor`)
    REFERENCES `mydb`.`Diretor` (`idDiretor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

--Pais
INSERT INTO Pais (nome_pais, DDI)
VALUES ("Brasil", 55);

INSERT INTO Pais (nome_pais, DDI)
VALUES ("Argentina", 54);

INSERT INTO Pais (nome_pais, DDI)
VALUES ("EUA", 1);

---

--UF
INSERT INTO UF (nome_uf, Pais_id_pais)
VALUES ("São Paulo", 1);

INSERT INTO UF (nome_uf, Pais_id_pais)
VALUES ("Rio de Janeiro", 1);

INSERT INTO UF (nome_uf, Pais_id_pais)
VALUES ("Buenos Aires", 2);

INSERT INTO UF (nome_uf, Pais_id_pais)
VALUES ("California", 3);

--
--Cidade

INSERT INTO Cidade (nome_cidade, DDD, UF_id_uf, UF_Pais_id_pais)
VALUES ("São Paulo",11, 1, 1);

INSERT INTO Cidade (nome_cidade, DDD, UF_id_uf, UF_Pais_id_pais)
VALUES ("Rio de Janeiro",21, 2, 1);

INSERT INTO Cidade (nome_cidade, DDD, UF_id_uf, UF_Pais_id_pais)
VALUES ("Buenos Aires", 11, 3, 2);

INSERT INTO Cidade (nome_cidade, DDD, UF_id_uf, UF_Pais_id_pais)
VALUES ("Los Angeles", 323, 4, 3);
---
---Bairro
INSERT INTO Bairro (nome_bairro, Cidade_id_cidade, Cidade_UF_id_uf, Cidade_UF_Pais_id_pais)
VALUES ("Parelheiros",1,1,1);

INSERT INTO Bairro (nome_bairro, Cidade_id_cidade, Cidade_UF_id_uf, Cidade_UF_Pais_id_pais)
VALUES ("Leblon",2,2,1);

INSERT INTO Bairro (nome_bairro, Cidade_id_cidade, Cidade_UF_id_uf, Cidade_UF_Pais_id_pais)
VALUES ("La Boca",3,3,2);

INSERT INTO Bairro (nome_bairro, Cidade_id_cidade, Cidade_UF_id_uf, Cidade_UF_Pais_id_pais)
VALUES ("Compton",4,4,3);
---
---Rua
INSERT INTO Rua (cep_rua,nome_rua,Bairro_id_bairro ,Bairro_Cidade_id_cidade, Bairro_Cidade_UF_id_uf, Bairro_Cidade_UF_Pais_id_pais)
VALUES (78951,"Rua do pao",1,1,1,1);

INSERT INTO Rua (cep_rua,nome_rua,Bairro_id_bairro ,Bairro_Cidade_id_cidade, Bairro_Cidade_UF_id_uf, Bairro_Cidade_UF_Pais_id_pais)
VALUES (99512,"Rua da margarina",2,2,2,1);

INSERT INTO Rua (cep_rua,nome_rua,Bairro_id_bairro ,Bairro_Cidade_id_cidade, Bairro_Cidade_UF_id_uf, Bairro_Cidade_UF_Pais_id_pais)
VALUES (74122,"Rua do joaozito",3,3,3,2);

INSERT INTO Rua (cep_rua,nome_rua,Bairro_id_bairro ,Bairro_Cidade_id_cidade, Bairro_Cidade_UF_id_uf, Bairro_Cidade_UF_Pais_id_pais)
VALUES (92124,"California love",4,4,4,3);
---
---TipoEndereco
INSERT INTO TipoEndereco (descricao_tipo_endereco)
VALUES ("Residencial");

INSERT INTO TipoEndereco (descricao_tipo_endereco)
VALUES ("Comercial");
---
---TipoTelefone
INSERT INTO TipoTelefone (descricao_tipo_telefone)
VALUES ("Residencial");

INSERT INTO TipoTelefone (descricao_tipo_telefone)
VALUES ("Comercial");
---
---Sexo
INSERT INTO Sexo (descricao_sexo)
VALUES ("Masculino");

INSERT INTO Sexo (descricao_sexo)
VALUES ("Feminino");
---
---EstadoCivil
INSERT INTO EstadoCivil (descricao_estado_civil)
VALUES ("Casado");

INSERT INTO EstadoCivil (descricao_estado_civil)
VALUES ("Solteiro");
---
---DonoEstudio
INSERT INTO DonoEstudio (cpf_dono, nome_dono,EstadoCivil_id_estado_civil, Sexo_id_sexo)
VALUES (7562148,"Magnata", 2, 1);

INSERT INTO DonoEstudio (cpf_dono, nome_dono,EstadoCivil_id_estado_civil, Sexo_id_sexo)
VALUES (467891,"Libélula", 1, 2);
---
---Diretor
INSERT INTO Diretor (cpf_diretor, nome_diretor,EstadoCivil_id_estado_civil, Sexo_id_sexo,Cidade_id_cidade , Cidade_UF_id_uf ,Cidade_UF_Pais_id_pais)
VALUES (468123,"David Fincher", 1, 1,1,1,1);

INSERT INTO Diretor (cpf_diretor, nome_diretor,EstadoCivil_id_estado_civil, Sexo_id_sexo,Cidade_id_cidade ,Cidade_UF_id_uf ,Cidade_UF_Pais_id_pais)
VALUES (563214,"Christopher Nolan", 1, 1,1,1,1);
---
---Ator
INSERT INTO Ator (cpf_ator, nome_artistico_ator,seguro_social_ator,data_nascimento_ator,EstadoCivil_id_estado_civil, Sexo_id_sexo,Cidade_id_cidade, Cidade_UF_id_uf, Cidade_UF_Pais_id_pais)
VALUES (566118," Matthew McConaughey",88888888,'1997-12-01', 1, 1, 1, 1, 1);
INSERT INTO Ator (cpf_ator, nome_artistico_ator,seguro_social_ator,data_nascimento_ator,EstadoCivil_id_estado_civil, Sexo_id_sexo,Cidade_id_cidade, Cidade_UF_id_uf, Cidade_UF_Pais_id_pais)
VALUES (94898445," Jaozin da Lapa",5552221,'1989-01-12', 1, 1, 1, 1, 1);
INSERT INTO Ator (cpf_ator, nome_artistico_ator,seguro_social_ator,data_nascimento_ator,EstadoCivil_id_estado_civil, Sexo_id_sexo,Cidade_id_cidade, Cidade_UF_id_uf, Cidade_UF_Pais_id_pais)
VALUES (123466,"Brad Pitt",885456,'1990-01-12', 1, 2, 2, 2, 1);
---
---Papel
INSERT INTO Papel (descricao_papel)
VALUES ("Mocinho");
INSERT INTO Papel (descricao_papel)
VALUES ("Vilao");
---
---AtorPapel
INSERT INTO AtorPapel (Ator_id_ator, Papel_id_papel)
VALUES (1,1);
INSERT INTO AtorPapel (Ator_id_ator, Papel_id_papel)
VALUES (2,1);
INSERT INTO AtorPapel (Ator_id_ator, Papel_id_papel)
VALUES (3,2);
---
---Estudio
INSERT INTO Estudio (nome_estudio,data_fundacao_estudio,faturamento_ano_anterior,DonoEstudio_id_dono_estudio)
VALUES ("Warner",'1989-05-02',9555552.2,1);
INSERT INTO Estudio (nome_estudio,data_fundacao_estudio,faturamento_ano_anterior,DonoEstudio_id_dono_estudio)
VALUES ("Paramount",'1990-10-02',99571121.2,2);
---
---Filme
INSERT INTO Filme (nome_filme,copyright_filme,qtd_meses_producao,ano_lancamento,custo_total_producao,Estudio_id_estudio)
VALUES ("A vida é insana","ABCltda",36,'2015',9998522143.22,1);
INSERT INTO Filme (nome_filme,copyright_filme,qtd_meses_producao,ano_lancamento,custo_total_producao,Estudio_id_estudio)
VALUES ("O retorno do infinito","ABCltda",48,'1989',999852214553.22,2);
--
--FilmeDiretor
INSERT INTO FilmeDiretor (Filme_id_filme, Diretor_idDiretor)
VALUES (1,1);
INSERT INTO FilmeDiretor (Filme_id_filme, Diretor_idDiretor)
VALUES (2,2);
--
--ContratoAtorFilme
INSERT INTO ContratoAtorFilme (cache_ator,Filme_id_filme, Ator_id_ator)
VALUES (888545.2,1,1);
INSERT INTO ContratoAtorFilme (cache_ator,Filme_id_filme, Ator_id_ator)
VALUES (55999555.2,2,2);
INSERT INTO ContratoAtorFilme (cache_ator,Filme_id_filme, Ator_id_ator)
VALUES (88999555.2,2,3);
---
---Personagem
INSERT INTO Personagem (nome_personagem,Sexo_id_sexo, ContratoAtorFilme_Filme_id_filme, ContratoAtorFilme_Ator_id_ator)
VALUES ("Loucao da vila",1,1,1);
INSERT INTO Personagem (nome_personagem,Sexo_id_sexo, ContratoAtorFilme_Filme_id_filme, ContratoAtorFilme_Ator_id_ator)
VALUES ("Aviador",1,2,2);
INSERT INTO Personagem (nome_personagem,Sexo_id_sexo, ContratoAtorFilme_Filme_id_filme, ContratoAtorFilme_Ator_id_ator)
VALUES ("Pescadora",2,2,3);
---
---Telefone
INSERT INTO Telefone (numero_telefone,TipoTelefone_id_tipo_telefone, DonoEstudio_id_dono_estudio,Diretor_idDiretor,Estudio_id_estudio,Ator_id_ator)
VALUES ("6199999999",2,1,1,1,1);
INSERT INTO Telefone (numero_telefone,TipoTelefone_id_tipo_telefone, DonoEstudio_id_dono_estudio,Diretor_idDiretor,Estudio_id_estudio,Ator_id_ator)
VALUES ("6199998888",1,2,2,2,2);
---
---Endereço
INSERT INTO Endereco (Rua_id_rua,Rua_Bairro_id_bairro,Rua_Bairro_Cidade_id_cidade,Rua_Bairro_Cidade_UF_id_uf,Rua_Bairro_Cidade_UF_Pais_id_pais,TipoEndereco_id_tipo_Endereco,Diretor_idDiretor,Estudio_id_estudio,Ator_id_ator,DonoEstudio_id_dono_estudio)
VALUES (1,1,1,1,1,1,1,1,1,1);
INSERT INTO Endereco (Rua_id_rua,Rua_Bairro_id_bairro,Rua_Bairro_Cidade_id_cidade,Rua_Bairro_Cidade_UF_id_uf,Rua_Bairro_Cidade_UF_Pais_id_pais,TipoEndereco_id_tipo_Endereco,Diretor_idDiretor,Estudio_id_estudio,Ator_id_ator,DonoEstudio_id_dono_estudio)
VALUES (1,1,1,1,1,2,2,2,2,2);

SELECT * FROM Filme
WHERE Estudio_id_estudio = 1;

SELECT ContratoAtorFilme.cache_ator
FROM ContratoAtorFilme
WHERE Ator_id_ator = 1;

SELECT Diretor.nome_diretor
FROM FilmeDiretor
INNER JOIN Diretor
ON FilmeDiretor.Diretor_idDiretor = Diretor.idDiretor;

SELECT Ator.nome_artistico_ator
FROM Ator
INNER JOIN ContratoAtorFilme
ON Ator.id_ator = ContratoAtorFilme.Ator_id_ator;
